Repository RedHatInsights/insights-advisor-frontend, pull requests merged in 2018-09, with the labels that each got.

#28 chore/disambiguate lockfile
  yarn.lock
Labels: bug

#30 Updating layout and pages to use new chroming service
  package-lock.json
  package.json
  src/App.scss
  src/Routes.js
  src/SmartComponents/Actions/ActionsOverview.js
  src/SmartComponents/Actions/ListActions.js
  src/SmartComponents/Actions/ViewActions.js
  src/SmartComponents/Actions/_actions.scss
  src/SmartComponents/Rules/ListRules.js
  src/index.html
Labels: on hold

#29 Correctly names stylintrc.json, adds default warning
  .stylelintrc.json
  package.json
Labels: bug

#32 Adds redux-y helpful debugging tools and support for es6 linting
  .eslintrc.yml
  mockData/actions-types-ids_impacted-systems.json
  package-lock.json
  package.json
  src/App.js
  src/AppActions.js
  src/AppConstants.js
  src/AppReducer.js
  src/SmartComponents/Actions/ListActions.js
  src/SmartComponents/Actions/ViewActions.js
  src/SmartComponents/Rules/ListRules.js
  src/Utilities/ReducerRegistry.js
  src/entry-dev.js
  src/entry.js
  src/store/index.js
Labels: enhancement

#35 Updating markup to reflect new linting rules
  .eslintrc.yml
  config/base.webpack.plugins.js
  package-lock.json
  package.json
  src/App.js
  src/PresentationalComponents/RulesCard/RulesCard.js
  src/PresentationalComponents/Skeletons/RulesCard/RulesCardSkeleton.js
  src/PresentationalComponents/SummaryChart/SummaryChart.test.js
  src/PresentationalComponents/SummaryChartItem/SummaryChartItem.js
  src/Routes.js
  src/SmartComponents/Actions/Actions.js
  src/SmartComponents/Actions/ActionsOverview.js
  src/SmartComponents/Actions/ListActions.js
  src/SmartComponents/Actions/ViewActions.js
  src/SmartComponents/Rules/Rules.js
  src/Utilities/asyncComponent.js
  src/entry-dev.js
  src/entry.js
Labels: enhancement

#36 Adds action url title helper, ensures urls match beta
  src/SmartComponents/Actions/ActionsOverview.js
  src/SmartComponents/Actions/ViewActions.js
Labels: bug

#37 Update nonbreaking deps
  package-lock.json
  package.json
Labels: bug

#39 Updates more deps
  package-lock.json
  package.json
  src/PresentationalComponents/RulesCard/RulesCard.js
  src/SmartComponents/Actions/ActionsOverview.js
  src/SmartComponents/Rules/ViewRule.js
Labels: bug

#41 adding title to listActions page
  src/SmartComponents/Actions/ListActions.js
Labels: enhancement

#42 Prevents undefined prop error in listactions component
  src/SmartComponents/Actions/ListActions.js
Labels: bug

#43 Adds api utility using axios, renames store folder to Store
  package-lock.json
  package.json
  src/Store/index.js
  src/Utilities/Api.js
  src/entry-dev.js
  src/entry.js
Labels: enhancement

#49 Adds license,author,repo to package.json
  package.json
Labels: enhancement

#44 Adds API support to ActionsOverview component
  README.md
  config/spandx.config.js
  src/AppActions.js
  src/AppConstants.js
  src/AppReducer.js
  src/PresentationalComponents/Loading/Loading.js
  src/SmartComponents/Actions/ActionsOverview.js
  src/Utilities/Api.js
Labels: enhancement
