Repository RedHatInsights/insights-advisor-frontend, pull requests merged in 2019-04, with the labels that each got.

#263 Updating battery to take up required space
  package-lock.json
  package.json
Labels: bug

#262 Adds routes for access rule and inventory, without category or severity
  src/SmartComponents/Actions/Actions.js
Labels: enhancement

#264 Adds external link icon to kba article
  package-lock.json
  package.json
  src/PresentationalComponents/RuleDetails/RuleDetails.js
Labels: bug

#266 Update release process to work for all branches (sans prod)
  .travis/custom_release.sh
Labels: bug

#265 Supports limit/offset and new api response format
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: enhancement

#267 Resolves TypeError: "this.buildNav is not a function"
  src/App.js
Labels: bug

#269 Resync with starter application Cloud fixes/refactor
  config/webpack.common.js
  src/Utilities/getBaseName.js
  src/entry-dev.js
  src/entry.js
  src/index.html
Labels: bug

#271 Updates insights inventory app to conform to new api endpoint 🙇🏾‍♀️
  package-lock.json
  package.json
Labels: bug

#270 When page changed to offset, base value went from 1 to 0 🌮
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: bug

#272 move FilterDropdown and FilterInput to insights-frontend-components
  package-lock.json
  package.json
  src/PresentationalComponents/Filters/FilterDropdown.js
  src/PresentationalComponents/Filters/FilterInput.js
  src/PresentationalComponents/Filters/Filters.js
  src/PresentationalComponents/Filters/_dropdown.scss
Labels: enhancement

#273 Listrules rule table will display impacted systems by default
  src/SmartComponents/Rules/ListRules.js
Labels: enhancement

#275 Resolves routing issues for `/insights`, `/insights/` and `/insights/actions`
  src/PresentationalComponents/Charts/ActionsOverviewDonut.js
  src/Routes.js
  src/Utilities/getBaseName.js
Labels: bug

#276 "Hosts" to "Systems" as per ux
  src/SmartComponents/Actions/ViewActions.js
Labels: bug

#277 Updates patternfly and other nonbreaking deps
  package-lock.json
  package.json
Labels: bug

#278 Refactors "actions" to "overview" and updates url
  src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
  src/PresentationalComponents/Charts/OverviewDonut.js
  src/PresentationalComponents/Charts/OverviewDonut.scss
  src/PresentationalComponents/Charts/SummaryChart/SummaryChartItem.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/Routes.js
  src/SmartComponents/Actions/Actions.js
  src/SmartComponents/Overview/Dashboard.js
  src/SmartComponents/Overview/Details.js
  src/SmartComponents/Overview/List.js
  src/SmartComponents/Overview/Overview.js
Labels: bug

#279 Separates /stats into /stats/rules and /stats/systems
  src/AppActions.js
  src/AppConstants.js
  src/AppReducer.js
  src/SmartComponents/Overview/Dashboard.js
Labels: enhancement

#280 Remove "other rules related to" (no topics for summit)
  src/PresentationalComponents/RuleDetails/RuleDetails.js
Labels: bug

#281 The risk of change should be stacked like total risk above
  src/PresentationalComponents/RuleDetails/RuleDetails.js
Labels: bug

#282 Refactor severity chart to rely on props rather than local state
  src/SmartComponents/Overview/Dashboard.js
Labels: bug

#283 Remove loading text from async cpt, adds spacing to no hits chart
  src/PresentationalComponents/Charts/SummaryChart/SummaryChart.js
  src/Utilities/asyncComponent.js
Labels: bug

#284 Relocates remediate with ansible button to inside inv table
  src/PresentationalComponents/Inventory/Inventory.js
  src/SmartComponents/Overview/Details.js
Labels: bug

#285 Removes external link icon markup from reports, it was breaking prod
  package-lock.json
  package.json
Labels: bug

#287 Updates deps, fixes loony breadcrumbs
  package-lock.json
  package.json
  src/PresentationalComponents/Breadcrumbs/_breadcrumbs.scss
Labels: bug, enhancement

#288 SVG needs react to be defined (in the constants file)
  src/AppConstants.js
Labels: bug

#289 Just a wip for the sake of wipping
  src/PresentationalComponents/Filters/Filters.js
  src/PresentationalComponents/MessageState/MessageState.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/SmartComponents/Overview/List.js
Labels: enhancement

#290 Add api static assets
  static/drf-yasg/immutable.min.js
  static/drf-yasg/insQ.min.js
  static/drf-yasg/redoc-init.js
  static/drf-yasg/redoc-old/redoc.min.js
  static/drf-yasg/redoc/redoc-logo.png
  static/drf-yasg/redoc/redoc.min.js
  static/drf-yasg/style.css
  static/drf-yasg/swagger-ui-dist/absolute-path.js
  static/drf-yasg/swagger-ui-dist/favicon-32x32.png
  static/drf-yasg/swagger-ui-dist/index.js
  static/drf-yasg/swagger-ui-dist/oauth2-redirect.html
  static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js
  static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js
  static/drf-yasg/swagger-ui-dist/swagger-ui.css
  static/drf-yasg/swagger-ui-init.js
  static/drf-yasg/url-polyfill.min.js
  static/rest_framework/css/bootstrap-theme.min.css
  static/rest_framework/css/bootstrap-tweaks.css
  static/rest_framework/css/bootstrap.min.css
  static/rest_framework/css/default.css
  static/rest_framework/css/font-awesome-4.0.3.css
  static/rest_framework/css/prettify.css
  static/rest_framework/docs/css/base.css
  static/rest_framework/docs/css/highlight.css
  static/rest_framework/docs/css/jquery.json-view.min.css
  static/rest_framework/docs/img/favicon.ico
  static/rest_framework/docs/img/grid.png
  static/rest_framework/docs/js/api.js
  static/rest_framework/docs/js/highlight.pack.js
  static/rest_framework/docs/js/jquery.json-view.min.js
  static/rest_framework/fonts/fontawesome-webfont.eot
  static/rest_framework/fonts/fontawesome-webfont.svg
  static/rest_framework/fonts/fontawesome-webfont.ttf
  static/rest_framework/fonts/fontawesome-webfont.woff
  static/rest_framework/fonts/glyphicons-halflings-regular.eot
  static/rest_framework/fonts/glyphicons-halflings-regular.svg
  static/rest_framework/fonts/glyphicons-halflings-regular.ttf
  static/rest_framework/fonts/glyphicons-halflings-regular.woff
  static/rest_framework/fonts/glyphicons-halflings-regular.woff2
  static/rest_framework/img/glyphicons-halflings-white.png
  static/rest_framework/img/glyphicons-halflings.png
  static/rest_framework/img/grid.png
  static/rest_framework/js/ajax-form.js
  static/rest_framework/js/bootstrap.min.js
  static/rest_framework/js/coreapi-0.1.1.js
  static/rest_framework/js/csrf.js
  static/rest_framework/js/default.js
  static/rest_framework/js/jquery-3.3.1.min.js
  static/rest_framework/js/prettify-min.js
Labels: enhancement

#292 Change empty state text as per ux guidance
  src/SmartComponents/Overview/Dashboard.js
Labels: enhancement

#295 Fixes expandable table compact missing blue border issue
  package-lock.json
  package.json
Labels: bug

#294 Bolds impact and likelihood
  src/PresentationalComponents/RuleDetails/RuleDetails.js
Labels: enhancement

#297 Increase cellwidth of added column
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: bug

#298 Adds react core styles to insights app
  src/App.scss
Labels: bug

#299 Roll back react-table update in order to fix styling issue
  package-lock.json
  package.json
Labels: bug

#296 Enhancement/rhcloud 975 gray boxes
  src/AppConstants.js
  src/AppSvgs.js
  src/PresentationalComponents/MessageState/MessageState.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/SmartComponents/Overview/Dashboard.js
Labels: enhancement

#300 Ends up we don't need itemsStart for pagination component
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: bug

#301 KBA link opens in new tab/window
  src/PresentationalComponents/RuleDetails/RuleDetails.js
Labels: enhancement

#303 Swaps dashboard gallery for level
  src/SmartComponents/Overview/Dashboard.js
  src/SmartComponents/Overview/Dashboard.scss
Labels: enhancement

#302 As per ux design, going with large table rather than compact
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: bug

#304 Use attribute publish_at, when the rule was published for added column
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: bug

#305 Adds padding between the charts when collapsed
  src/SmartComponents/Overview/Dashboard.js
  src/SmartComponents/Overview/Dashboard.scss
Labels: bug

#306 Fixes rendering only the first ul correctly
  package-lock.json
  package.json
Labels: bug

#308 Update table dep and adds external link icon to rule reports
  package-lock.json
  package.json
Labels: bug

#309 Removes external icon on reports, broken likely react-dom prod version
  package-lock.json
  package.json
Labels: bug

#307 Moves rule details inventory table title outside of card
  src/SmartComponents/Overview/Details.js
  src/SmartComponents/Overview/Details.scss
Labels: bug
