Repository RedHatInsights/insights-advisor-frontend, pull requests merged in 2019-03, with the labels that each got.

#215 Centers action table cells that have icons
  src/SmartComponents/Actions/ViewActions.js
Labels: enhancement

#216 When active rule index is 0 ensure we display it first
  package-lock.json
  package.json
Labels: bug

#217 Abstracts ruletable to component, sets rules/actions lists to consume
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/SmartComponents/Actions/ViewActions.js
  src/SmartComponents/Actions/_actions.scss
  src/SmartComponents/Rules/ListRules.js
Labels: enhancement

#220 Update TableToolbar component, maintain pagination right justified
  config/base.webpack.plugins.js
  package-lock.json
  package.json
  src/PresentationalComponents/Filters/Filters.js
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: bug

#218 Codebase pruning, general cleanup
  src/PresentationalComponents/Cards/RulesCard.js
  src/PresentationalComponents/Cards/_RulesCard.scss
  src/PresentationalComponents/Charts/SummaryChart/SummaryChart.js
  src/PresentationalComponents/Charts/SummaryChart/SummaryChart.test.js
  src/PresentationalComponents/Charts/SummaryChart/SummaryChartItem.js
  src/PresentationalComponents/Charts/SummaryChart/SummaryChartItem.scss
  src/PresentationalComponents/Charts/SummaryChart/SummaryChartItem.test.js
  src/PresentationalComponents/Skeletons/RulesCard/RulesCardSkeleton.js
  src/PresentationalComponents/Skeletons/_Skeleton.scss
  src/SmartComponents/Actions/Actions.js
  src/SmartComponents/Actions/ActionsOverview.js
  src/SmartComponents/Actions/ListActions.js
  src/SmartComponents/Actions/ViewActions.js
  src/SmartComponents/Actions/_actions.scss
  src/SmartComponents/Rules/Rules.js
  src/SmartComponents/Rules/ViewRule.js
  src/SmartComponents/Rules/_rules.scss
Labels: enhancement

#208 Adds sorting for systems count and ansible columns to actions table
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: enhancement

#221 Toggling impacting stays sane when on a page !== 1
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: bug

#213 Add RuleDetails component
  src/AppConstants.js
  src/PresentationalComponents/RuleDetails/RuleDetails.js
  src/PresentationalComponents/RuleDetails/_RuleDetails.scss
  src/SmartComponents/Actions/ViewActions.js
Labels: enhancement

#219 Adds expandable table to rules table
  src/AppConstants.js
  src/PresentationalComponents/RuleDetails/RuleDetails.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/SmartComponents/Actions/ViewActions.js
Labels: enhancement

#223 Adds header to kba request, avoids throwing an xml parsing error in ff
  src/PresentationalComponents/RuleDetails/RuleDetails.js
Labels: bug

#222 Update them deps, remove some we don't use anymore
  package-lock.json
  package.json
Labels: enhancement

#224 Fix capitalization of List Action page titles
  src/SmartComponents/Actions/ListActions.js
Labels: bug

#225 A filter should only ever be set if one exists (to be set)
  src/PresentationalComponents/Filters/Filters.js
Labels: bug

#229 Title.split creates array, address by index, fixes overview chart nav
  src/SmartComponents/Actions/ListActions.js
Labels: bug

#228 Swaps .flat for flatten, ff60.5.2 compatability, no visual changes
  .babelrc
Labels: bug

#227 Updating Actions Overview and Donut
  src/App.scss
  src/PresentationalComponents/Charts/ActionsOverviewDonut.js
  src/PresentationalComponents/Charts/ActionsOverviewDonut.scss
  src/PresentationalComponents/Charts/SummaryChart/SummaryChart.js
  src/SmartComponents/Actions/ActionsOverview.js
Labels: enhancement

#232 Sorting happens by column index, not by those that are sorting
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: bug

#233 Gonna just rely on lodash to flatten the rules array
  .babelrc
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: bug

#231 Filter by show_reports
  src/AppConstants.js
  src/PresentationalComponents/Filters/CheckboxFilter.js
  src/PresentationalComponents/Filters/FilterDropdown.js
  src/PresentationalComponents/Filters/FilterInput.js
  src/PresentationalComponents/Filters/Filters.js
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: enhancement

#226 Adds enabling/disabling reporting on a rule
  package-lock.json
  package.json
  src/AppConstants.js
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: enhancement

#234 Convert all paths to the cloud.redhat.com paths
  README.md
  config/base.webpack.plugins.js
  config/spandx.config.js
  config/webpack.common.js
  src/App.js
  src/Routes.js
  src/entry-dev.js
  src/entry.js
  src/index.html
Labels: enhancement

#236 Adds missing root to public path
  config/webpack.common.js
Labels: bug

#237 Update deps
  package-lock.json
  package.json
Labels: bug

#238 Update api path, app identifier, host 🌧
  config/spandx.config.js
  src/App.js
  src/AppConstants.js
Labels: bug, cloud

#239 Update app to support beta branch release as per cloud migration guide
  src/entry-dev.js
  src/entry.js
Labels: enhancement

#240 Use correct dynamic basename
  src/Routes.js
  src/entry-dev.js
  src/entry.js
Labels: bug, cloud

#241 Updates inventory to version that has the correct (most current) api url
  package-lock.json
  package.json
Labels: cloud, enhancement

#242 Fixes broken kba links does away with unnecessary common header
  src/PresentationalComponents/RuleDetails/RuleDetails.js
  src/Utilities/Api.js
Labels: bug

#244 Update deps
  package-lock.json
  package.json
Labels: enhancement

#245 Fixes show_reports, ends up its a delete with the rule_id in url
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/Utilities/Api.js
Labels: bug

#251 Removes a few unnecessary divs, adds label to donut legend
  src/PresentationalComponents/Charts/ActionsOverviewDonut.js
Labels: bug

#252 Restores donut outer most div, dashboard doesn't scale well without
  src/PresentationalComponents/Charts/ActionsOverviewDonut.js
Labels: bug

#246 Resets page to 1 whenever any filtering is performed, keeps the api 😊
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: bug

#247 Incorrectly displaying 0 for remediation button when playbook_count === 0
  src/SmartComponents/Actions/ViewActions.js
Labels: bug

#249 Discrepancy in Ansible support indication between insights and inventory
  package-lock.json
  package.json
Labels: bug

#254 Fixes rule resolution content consolidated to single line
  package-lock.json
  package.json
Labels: bug

#255 Reword show/hide reports to enable/disable rule, attribute not changing😢
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: bug

#256 Automatically release beta when we push to master
  .travis/custom_release.sh
Labels: enhancement

#258 Update readme to detail IF branches/deploy process
  README.md
Labels: enhancement

#261 playbook_count is a num, not an array, fixes the remediation button
  src/SmartComponents/Actions/ViewActions.js
Labels: bug

#257 Enhancement/update severity chart
  package.json
  src/PresentationalComponents/Charts/SummaryChart/SummaryChart.js
  src/PresentationalComponents/Charts/SummaryChart/SummaryChart.scss
  src/PresentationalComponents/Charts/SummaryChart/SummaryChart.test.js
  src/PresentationalComponents/Charts/SummaryChart/SummaryChartItem.js
  src/PresentationalComponents/Charts/SummaryChart/SummaryChartItem.scss
  src/PresentationalComponents/Charts/SummaryChart/SummaryChartItem.test.js
  src/SmartComponents/Actions/ActionsOverview.js
Labels: enhancement, ux/review

#260 Adds ocp system type for risk of change reporting on rule details page
  src/AppConstants.js
  src/PresentationalComponents/RuleDetails/RuleDetails.js
Labels: enhancement

#259 Adds empty state to donut (when totalhits = 0)
  src/PresentationalComponents/Charts/ActionsOverviewDonut.js
Labels: enhancement, ux/review
