Repository RedHatInsights/insights-advisor-frontend, pull requests merged in 2019-01, with the labels that each got.

#119 Adds pagination/filtering to inventory table
  src/PresentationalComponents/Inventory/Inventory.js
Labels: enhancement

#125 Update deps
  package-lock.json
  package.json
  src/PresentationalComponents/Inventory/InventoryRuleList.js
Labels: enhancement

#127 Inv component needs array of strings, returned by /systems on host_ids
  src/SmartComponents/Actions/ListActions.js
Labels: bug

#128 Update deps
  package-lock.json
  package.json
Labels: enhancement

#130 Updates deps
  package-lock.json
  package.json
Labels: bug

#132 Updates loading component adds Failed component
  package-lock.json
  package.json
  src/PresentationalComponents/Loading/Failed.js
  src/PresentationalComponents/Loading/Loading.js
  src/SmartComponents/Actions/ListActions.js
  src/SmartComponents/Actions/ViewActions.js
Labels: enhancement

#131 Removes configuration assessment component
  package-lock.json
  package.json
  src/AppReducer.js
  src/PresentationalComponents/Cards/ExpandableRulesCard.js
  src/PresentationalComponents/Inventory/InventoryRuleList.js
Labels: enhancement, wip

#134 Update deps
  package-lock.json
  package.json
Labels: enhancement

#135 Adds vulnerabilities info component to inv details screen
  src/AppReducer.js
Labels: enhancement

#137 send rule description to remediation wizard
  src/SmartComponents/Actions/ListActions.js
Labels: enhancement

#138 Removes depreciate _html attribute and process md/html on client
  package-lock.json
  package.json
  src/PresentationalComponents/Cards/RulesCard.js
  src/SmartComponents/Actions/ListActions.js
  src/SmartComponents/Rules/ListRules.js
Labels: enhancement

#139 Update deps
  package-lock.json
  package.json
Labels: enhancement

#140 Update deps
  package-lock.json
  package.json
Labels: enhancement

#142 Update deps
  package-lock.json
  package.json
Labels: enhancement

#143 Update deps
  package-lock.json
  package.json
Labels: bug

#144 Ensure valid non-null input for reactmarkdown
  package-lock.json
  package.json
  src/PresentationalComponents/Cards/RulesCard.js
  src/SmartComponents/Actions/ListActions.js
Labels: bug

#146 Cleans up donut chart tspan errors
  src/PresentationalComponents/Charts/ActionsOverviewDonut.js
Labels: bug

#145 Update resolution_risk to use rhel .risk value
  src/AppConstants.js
  src/SmartComponents/Actions/ListActions.js
  src/SmartComponents/Rules/ListRules.js
Labels: enhancement

#147 Correct spacing around breadcrumbs
  package-lock.json
  src/PresentationalComponents/Breadcrumbs/_breadcrumbs.scss
  src/SmartComponents/Actions/ListActions.js
  src/SmartComponents/Actions/ViewActions.js
Labels: bug

#149 Refactor breadcrumbs to make them match based
  src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
  src/SmartComponents/Actions/ListActions.js
  src/SmartComponents/Actions/ViewActions.js
Labels: bug, enhancement

#151 Updates deps
  package-lock.json
  package.json
Labels: enhancement

#152 Refactor Breadcrumbs
  src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
  src/SmartComponents/Actions/ListActions.js
  src/SmartComponents/Actions/ViewActions.js
Labels: enhancement

#153 Update deps
  package-lock.json
  package.json
Labels: bug

#154 [WIP] Resolves PaginationRow Undefined error when loading inventory component
  src/PresentationalComponents/Inventory/Inventory.js
Labels: bug, wip

#148 Adds breadcrumbs and additional visual enhancements to inv details
  src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
  src/PresentationalComponents/Inventory/InventoryDetails.js
Labels: enhancement

#155 Followup to #154, fixes the undefined pagination row issue
  src/PresentationalComponents/Inventory/Inventory.js
Labels: bug

#156 Attribute naming is tricky, has_playbook true means not unsupported 🤦🏽‍♀️
  src/PresentationalComponents/Cards/RulesCard.js
  src/SmartComponents/Actions/ListActions.js
  src/SmartComponents/Actions/ViewActions.js
Labels: bug

#158 Adjusts responsive breakpoints/sizes for the Donut
  src/SmartComponents/Actions/ActionsOverview.js
Labels: bug

#159 Update deps
  package-lock.json
  package.json
Labels: enhancement

#160 BU directed the removal of vulnerabilities tab
  src/AppReducer.js
  src/PresentationalComponents/Inventory/InventoryDetails.js
Labels: bug

#162 Update deps
  package-lock.json
  package.json
Labels: enhancement

#164 Update deps
  package-lock.json
  package.json
Labels: bug

#161 Await successful user auth prior to interacting with api
  src/SmartComponents/Actions/ActionsOverview.js
Labels: bug

#163 Ensure prop type passed is one expected
  src/PresentationalComponents/Cards/RulesCard.js
Labels: bug

#167 Applies ICF #263
  package-lock.json
  package.json
Labels: bug

#166 Adds filtering rule list by those that have impacted systems
  src/SmartComponents/Rules/ListRules.js
Labels: enhancement

#168 Forces fixed victory container height for donut so we don't 😱🍩
  src/PresentationalComponents/Charts/ActionsOverviewDonut.js
  src/PresentationalComponents/Charts/ActionsOverviewDonut.scss
  src/SmartComponents/Actions/ActionsOverview.js
Labels: bug

#169 RHIADVISOR-400 fix inv rule sort, active rule always on top
  package-lock.json
  package.json
Labels: bug
