Repository RedHatInsights/insights-advisor-frontend, pull requests merged in 2019-05, with the labels that each got.

#310 Add pagination function to affected systems
  src/PresentationalComponents/Inventory/Inventory.js
Labels: bug

#312 Removes RHCSS from title
  src/index.html
Labels: bug

#315 Updates pf-table cell structure, needs `title:foo` to render component
  package-lock.json
  package.json
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: enhancement, post summit

#316 Swaps kba fetch for url build off node_id, Access handles the redirect
  src/PresentationalComponents/RuleDetails/RuleDetails.js
Labels: enhancement, post summit

#317 Updates deps
  package-lock.json
  package.json
Labels: bug

#318 Now all system detail bullets are the same size
  package-lock.json
  package.json
Labels: bug

#320 Changes dashboard link url
  src/SmartComponents/Overview/Dashboard.js
Labels: bug

#322 Updates system detail from card list to table
  package-lock.json
  package.json
Labels: enhancement

#321 Update title per BU guidance
  src/index.html
Labels: bug

#319 Use new frontend components monrepo packages
  package-lock.json
  package.json
  src/App.js
  src/App.scss
  src/AppReducer.js
  src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
  src/PresentationalComponents/Charts/SummaryChart/SummaryChart.scss
  src/PresentationalComponents/Charts/SummaryChart/SummaryChartItem.js
  src/PresentationalComponents/Filters/Filters.js
  src/PresentationalComponents/Inventory/Inventory.js
  src/PresentationalComponents/Inventory/InventoryDetails.js
  src/PresentationalComponents/RuleDetails/RuleDetails.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/SmartComponents/Overview/Dashboard.js
  src/SmartComponents/Overview/Details.js
  src/SmartComponents/Overview/Details.scss
  src/SmartComponents/Overview/List.js
  src/SmartComponents/Overview/Overview.js
  src/SmartComponents/Rules/ListRules.js
  src/SmartComponents/Rules/Rules.js
  src/Store/index.js
  src/entry-dev.js
  src/entry.js
Labels: enhancement

#323 Fixes kba article name missing from inv-insights report details
  package-lock.json
  package.json
Labels: bug

#324 Set default rules view to be sorted by newest first
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: enhancement

#326 Switch from flakey class to hardcoded style
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: bug

#328 onSort makes a FetchRules call, no need have a second one in didmount
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: bug

#329 Updates deps
  package-lock.json
  package.json
Labels: enhancement

#330 Apply external filters before fetching sorted rule list
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/SmartComponents/Overview/List.js
  src/SmartComponents/Rules/ListRules.js
Labels: bug

#331 Refactors system reports table, add sorting/filtering/searching
  config/base.webpack.plugins.js
  package-lock.json
  package.json
Labels: enhancement

#332 White-space pre-wrap fixes our text overflow issues for pre code blocks
  package-lock.json
  package.json
Labels: bug
