Repository RedHatInsights/insights-advisor-frontend, pull requests merged in 2020-01, with the labels that each got.

#516 Reconfigures rating cycle, updates deps
  package-lock.json
  package.json
  src/PresentationalComponents/RuleRating/RuleRating.js
Labels: bug

#517 Adds explicit labels to rating buttons
  src/PresentationalComponents/RuleRating/RuleRating.js
Labels: enhancement

#518 Wait to use insights global until it exists
  src/App.js
Labels: bug

#519 Fixes inventory table bottom pagination
  src/PresentationalComponents/Inventory/Inventory.js
Labels: bug

#520 Filtering by disabled rules auto sets impacting to false
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: enhancement

#521 Inv-table preserves page number after host ack
  src/PresentationalComponents/Inventory/Inventory.js
Labels: bug

#522 Updates primary toolbar, filter selector size, filter case
  package-lock.json
  package.json
Labels: enhancement

#523 Sets impacting=false on the "Include disabled rules" link, empty table 🦹‍♀️
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: bug

#524 Per page for inv-table also persists across inv-table changes 🌮
  src/PresentationalComponents/Inventory/Inventory.js
Labels: bug

#525 Minor UI tweak to improve automation
  src/PresentationalComponents/Charts/SummaryChart/SummaryChart.js
Labels: enhancement

#526 Adds total risk icons, description to filter chips, check ansible filter
  package-lock.json
  package.json
Labels: enhancement

#483 Add Topics Admin Table
  locales/data.json
  locales/translations.json
  src/AppActions.js
  src/Messages.js
  src/PresentationalComponents/Modals/AddEditTopic.js
  src/PresentationalComponents/Modals/_AddEditTopic.scss
  src/PresentationalComponents/TopicsAdminTable/TopicsAdminTable.js
  src/PresentationalComponents/TopicsAdminTable/_TopicsAdminTable.scss
Labels: enhancement

#527 Removes default 'additional info' from inv-insights table
  package-lock.json
  package.json
Labels: enhancement

#528 Swaps topics cards for a topics table
  locales/data.json
  locales/translations.json
  src/Messages.js
  src/PresentationalComponents/SystemsTable/SystemsTable.js
  src/PresentationalComponents/TopicCard/TopicCard.js
  src/PresentationalComponents/TopicCard/_TopicCard.scss
  src/PresentationalComponents/TopicsTable/TopicsTable.js
  src/SmartComponents/Topics/List.js
Labels: enhancement, ux/approved

#529 Ensure topic table no results message is centered
  src/PresentationalComponents/TopicsTable/TopicsTable.js
Labels: bug

#530 Grabs is_internal from identity.user
  src/SmartComponents/Topics/Topics.js
Labels: bug

#531 Primarytoolbar displays filter chip container only with chips
  package-lock.json
  package.json
Labels: bug

#532 Update Insights 0 state to include the 2 steps to get going with insights-client
  locales/data.json
  locales/translations.json
  src/Messages.js
  src/SmartComponents/Overview/Dashboard.js
  src/SmartComponents/Overview/Dashboard.scss
Labels: enhancement, ux/approved

#533 Inventory insights app now displays getting started for new systems
  package-lock.json
  package.json
Labels: enhancement

#534 Fix topics admin protected route - set a pattern for app route rbac
  package-lock.json
  package.json
  src/SmartComponents/Topics/Topics.js
Labels: bug

#535 Ends up safari doesn't like to put without a slash at the end 👨‍🏫🤷‍♀️
  src/PresentationalComponents/Modals/AddEditTopic.js
Labels: bug

#537 Breadcrumbs are no longer upper case
  src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
  src/PresentationalComponents/Breadcrumbs/_breadcrumbs.scss
Labels: enhancement

#538 Show filter chip for rule status, absent filter = all
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: enhancement

#539 Update deps, add default breadcrumb string
  package-lock.json
  package.json
  src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
Labels: bug, enhancement

#540 Replaces badge (incident/disabled) with label component
  locales/data.json
  locales/translations.json
  src/AppConstants.js
  src/AppReducer.js
  src/Messages.js
  src/PresentationalComponents/RuleLabels/RuleLabels.js
  src/PresentationalComponents/RuleLabels/_RuleLabels.scss
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/SmartComponents/Rules/Details.js
Labels: enhancement

#543 Rules default filter to not include incidents, update deps
  package-lock.json
  package.json
  src/AppReducer.js
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: bug
