Repository RedHatInsights/insights-advisor-frontend, pull requests merged in 2020-11, with the labels that each got.

#779 Fix switch in ClassicRedirect
  src/SmartComponents/Common/ClassicRedirect.js
Labels: bug

#780 Use consistent page titles across Insights - add subapp name to page titles
  src/Messages.js
  src/PresentationalComponents/Inventory/InventoryDetails.js
  src/SmartComponents/Recs/Details.js
  src/SmartComponents/Recs/List.js
  src/SmartComponents/Systems/List.js
  src/SmartComponents/Topics/Details.js
  src/SmartComponents/Topics/List.js
  src/index.html
Labels: enhancement

#781 Adds RBAC to view advisor, export data, disable rules
  locales/translations.json
  src/App.js
  src/AppConstants.js
  src/Messages.js
  src/PresentationalComponents/ExecutiveReport/Download.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/PresentationalComponents/SystemsTable/SystemsTable.js
  src/SmartComponents/Recs/Details.js
  src/SmartComponents/Recs/List.js
Labels: :shrug:, enhancement

#783 Update deps! 🐘
  package-lock.json
  package.json
Labels: tech debt

#785 Store the alert close action in local storage (.. and update deps)
  src/SmartComponents/Recs/List.js
Labels: bug
