Repository RedHatInsights/insights-advisor-frontend, pull requests merged in 2020-07, with the labels that each got.

#683 Changes rec table filter text
  locales/data.json
  locales/translations.json
  src/Messages.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/PresentationalComponents/RulesTable/_RulesTable.scss
Labels: :1st_place_medal:, bug

#684 Renames systable filterchip to name, rectable to recommendation
  locales/data.json
  locales/translations.json
  src/Messages.js
  src/PresentationalComponents/Common/Tables.js
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: bug

#685 When perpage is less than length, hide selection option (rec details)🛠
  src/PresentationalComponents/Inventory/Inventory.js
Labels: bug

#686 Make tags toolbar and modal like inventory
  src/AppConstants.js
  src/Messages.js
  src/PresentationalComponents/TagsToolbar/ManageTags.js
  src/PresentationalComponents/TagsToolbar/TagsList.js
  src/PresentationalComponents/TagsToolbar/TagsToolbar.js
  src/PresentationalComponents/TagsToolbar/_TagsToolbar.scss
Labels: :taco:, enhancement

#687 Force-trigger debounce to fetch tags on mount
  src/PresentationalComponents/TagsToolbar/TagsToolbar.js
Labels: :shrug:, :vampire_woman:, bug

#688 Pass react redux to inventory loader as well
  src/PresentationalComponents/Inventory/Inventory.js
  src/PresentationalComponents/Inventory/InventoryDetails.js
  src/PresentationalComponents/SystemsTable/SystemsTable.js
Labels: enhancement

#657 Changes required for Advisor to support pf4 updates
  package-lock.json
  package.json
  src/PresentationalComponents/Inventory/InventoryDetails.js
  src/PresentationalComponents/MessageState/MessageState.js
  src/PresentationalComponents/Modals/AddEditTopic.js
  src/PresentationalComponents/Modals/DisableRule.js
  src/PresentationalComponents/Modals/ViewHostAcks.js
  src/PresentationalComponents/RuleDetails/RuleDetails.js
  src/PresentationalComponents/RuleLabels/RuleLabels.js
  src/PresentationalComponents/RuleLabels/_RuleLabels.scss
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/PresentationalComponents/TagsToolbar/TagsToolbar.js
  src/PresentationalComponents/TopicsTable/TopicsTable.js
  src/SmartComponents/Recs/Details.js
  src/SmartComponents/Recs/List.js
  src/SmartComponents/Recs/_List.scss
  src/SmartComponents/Topics/Details.js
Labels: :taco:, enhancement

#689 Make dropdowns text only
  src/AppConstants.js
Labels: enhancement

#690 Update inv-insights app for pf4 support
  package-lock.json
  package.json
Labels: :waffle: :soap: :anchor: :namibia:, enhancement

#691 Add key=value to tags toolbar
  src/PresentationalComponents/TagsToolbar/TagsToolbar.js
  src/PresentationalComponents/TagsToolbar/_TagsToolbar.scss
Labels: enhancement

#692 Rec detail, ensure remediate button is disabled when no playbook
  src/PresentationalComponents/Inventory/Inventory.js
Labels: bug

#693 URI decode the tags tooltip
  src/PresentationalComponents/TagsToolbar/TagsToolbar.js
Labels: :1st_place_medal:, :star2:, bug

#694 Update grading system
  locales/data.json
  locales/translations.json
  package-lock.json
  package.json
  src/AppConstants.js
  src/Messages.js
  src/PresentationalComponents/RuleDetails/RuleDetails.js
  src/PresentationalComponents/RuleDetails/_RuleDetails.scss
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/SmartComponents/Recs/Details.js
  src/Utilities/intlHelper.js
Labels: :1st_place_medal:, :star2:, :taco:, enhancement

#697 Update a dep in order to bump the build in prod-beta
  package-lock.json
  package.json
Labels: enhancement

#699 Removes cve banner 🤙🏾🙂😆🤫🤭😵🤐🥴
  src/SmartComponents/Recs/List.js
  src/SmartComponents/Recs/_List.scss
Labels: enhancement

#701 Workaround for patternfly checkForValue.toString error in Select comp…
  src/PresentationalComponents/TagsToolbar/TagsToolbar.js
Labels: bug

#696 Add rule category to recommendation details component
  src/SmartComponents/Recs/Details.js
  src/SmartComponents/Recs/Details.scss
Labels: enhancement

#702 Remove the bell icon from the Disabled label
  src/PresentationalComponents/RuleLabels/RuleLabels.js
Labels: enhancement

#698 Update success color
  package-lock.json
  package.json
  src/PresentationalComponents/RuleDetails/_RuleDetails.scss
  src/PresentationalComponents/RulesTable/_RulesTable.scss
Labels: :shrug:, enhancement

#703 Update Battery text in PDF
  package-lock.json
  package.json
  src/PresentationalComponents/ExecutiveReport/Build.js
Labels: :taco:, enhancement

#705 Add filter chips to Tags Toolbar
  package-lock.json
  package.json
  src/PresentationalComponents/TagsToolbar/ManageTags.js
Labels: :vampire_woman:, enhancement

#704 Return all data from inventory tags endpoint
  src/PresentationalComponents/TagsToolbar/ManageTags.js
  src/PresentationalComponents/TagsToolbar/TagsToolbar.js
Labels: enhancement

#707 Update react-core to take in Select component fix. Remove workaround
  package-lock.json
  package.json
  src/PresentationalComponents/TagsToolbar/TagsToolbar.js
Labels: bug

#708 Maintain selected state across all ManagedTags modal open/closes
  src/PresentationalComponents/TagsToolbar/ManageTags.js
Labels: bug

#709 Update Inv-Insights dep
  package-lock.json
  package.json
Labels: :taco:, bug

#710 Convert populateSelected to be an expression
  src/PresentationalComponents/TagsToolbar/ManageTags.js
Labels: enhancement

#711 Correct rule details spacing
  src/PresentationalComponents/RuleDetails/RuleDetails.js
  src/PresentationalComponents/RuleDetails/_RuleDetails.scss
Labels: :star2:, bug

#713 Update deps and add custom styling to tags modal
  package-lock.json
  package.json
Labels: :taco:, bug

#714 Ensures rec details titles are bold
  src/PresentationalComponents/RuleDetails/RuleDetails.js
Labels: bug
