Repository RedHatInsights/insights-advisor-frontend, pull requests merged in 2020-08, with the labels that each got.

#716 Update deps cuz we haven't done it in a while 🥴⚡️
  package-lock.json
  package.json
Labels: :taco:, enhancement

#715 Don't truncate system table column headings
  src/PresentationalComponents/SystemsTable/SystemsTable.js
  src/PresentationalComponents/SystemsTable/SystemsTable.scss
Labels: :1st_place_medal:, :star2:, bug

#717 Pass pf react core to inventory to properly render inventory
  src/PresentationalComponents/Inventory/Inventory.js
  src/PresentationalComponents/Inventory/InventoryDetails.js
  src/PresentationalComponents/SystemsTable/SystemsTable.js
Labels: :1st_place_medal:, enhancement

#718 Make rec table upper pagination compact
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/PresentationalComponents/TopicsTable/TopicsTable.js
Labels: :vampire_woman:, bug

#719 Align items in Recs header
  src/SmartComponents/Recs/List.js
  src/SmartComponents/Recs/List.scss
Labels: :taco:, bug

#721 Update rule rating success color to align with ansible check
  src/PresentationalComponents/RuleRating/_RuleRating.scss
Labels: :waffle: :soap: :anchor: :namibia:, bug

#720 Center rec ansible column contents 🍔
  package-lock.json
  package.json
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/PresentationalComponents/RulesTable/_RulesTable.scss
Labels: bug

#722 Add InsightsLabel to PDF
  package-lock.json
  package.json
  src/PresentationalComponents/ExecutiveReport/Build.js
Labels: :star2:, :taco:, enhancement

#723 Add boolean to check if Rule value is up-to-date
  src/SmartComponents/Recs/Details.js
Labels: :waffle: :soap: :anchor: :namibia:, bug

#724 Remove name from text-input in DisableRule modal
  src/PresentationalComponents/Modals/DisableRule.js
Labels: :taco:, bug

#725 Add RemediationButton as dedicatedAction
  src/PresentationalComponents/Inventory/Inventory.js
Labels: :shrug:, :vampire_woman:, bug

#726 Update deps, fix remediation button icon color
  package-lock.json
  package.json
  src/PresentationalComponents/Inventory/Inventory.js
  src/PresentationalComponents/Inventory/_Inventory.scss
Labels: :waffle: :soap: :anchor: :namibia:, bug

#727 Title only on first page of SystemsPDF
  src/PresentationalComponents/Export/SystemsPdf.js
Labels: :godmode:, :taco:, enhancement

#728 Update RuleDetails for compact mode
  src/PresentationalComponents/RuleDetails/RuleDetails.js
  src/PresentationalComponents/RuleDetails/_RuleDetails.scss
  src/SmartComponents/Recs/Details.js
  src/SmartComponents/Recs/Details.scss
Labels: :taco:, bug

#729 Update remediation button n other nonbreaking deps 🤗
  .gitignore
  package-lock.json
  package.json
Labels: bug

#730 Prepends 'Advisor' to all page titles/breadcrumbs
  src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
  src/SmartComponents/Recs/List.js
  src/SmartComponents/Systems/List.js
  src/SmartComponents/Topics/List.js
Labels: :waffle: :soap: :anchor: :namibia:, enhancement

#732 Update sorting and width
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/PresentationalComponents/RulesTable/_RulesTable.scss
  src/PresentationalComponents/SystemsTable/SystemsTable.js
  src/SmartComponents/Recs/Details.js
Labels: :vampire_woman:, bug, on hold

#733 Update DisableRule modal and add Notifications
  src/Messages.js
  src/PresentationalComponents/Modals/DisableRule.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/SmartComponents/Recs/Details.js
Labels: :waffle: :soap: :anchor: :namibia:, bug

#736 Add timeout to disable/enable notifications
  src/PresentationalComponents/Modals/DisableRule.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/SmartComponents/Recs/Details.js
Labels: :taco:, bug

#737 fix(intl): Fix missing translation for "xx-XX" locale
  src/AppConstants.js
  src/entry-dev.js
  src/entry.js
Labels: :godmode:, :star2:, bug

#738 Include all inventory and remediations dependencies
  package-lock.json
  package.json
Labels: :1st_place_medal:, bug

#712 Update tags query
  src/AppActions.js
  src/PresentationalComponents/Common/Tables.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/SmartComponents/Recs/Details.js
Labels: :godmode:, enhancement, on hold

#739 Updates non-breaking deps, fixes ah build warning
  package-lock.json
  package.json
  src/App.js
Labels: :1st_place_medal:, tech debt

#740 Add tooltip to export icon
  package-lock.json
  package.json
  src/Messages.js
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: :taco:, enhancement

#741 Disable custom filter on beta branches or if localStorage is set
  src/App.js
  src/AppConstants.js
  src/SmartComponents/Recs/Details.js
  src/SmartComponents/Recs/List.js
  src/SmartComponents/Systems/List.js
  src/SmartComponents/Topics/Details.js
  src/SmartComponents/Topics/List.js
Labels: :taco:, enhancement

#742 Make systems table text conform to pf default
  src/PresentationalComponents/SystemsTable/SystemsTable.scss
Labels: :taco:, bug

#743 Removes 'undefined' as reports_shown url param (when applicable)
  src/PresentationalComponents/Common/Tables.js
Labels: :shrug:, enhancement
