Repository RedHatInsights/insights-advisor-frontend, pull requests merged in 2020-10, with the labels that each got.

#762 Updates non-breaking deps, ~pf-core is still borked~
  package-lock.json
  package.json
Labels: :shrug:, tech debt

#763 Filter out non-filterTypes from chips
  src/PresentationalComponents/Common/Tables.js
Labels: :taco:, bug

#764 Update onKeyPress for DisableRule Modal
  src/PresentationalComponents/Modals/DisableRule.js
Labels: bug

#765 Update deps🏴‍☠️
  package-lock.json
  package.json
Labels: tech debt

#766 No Recommendations text message reflects the selected rule status filter
  locales/translations.json
  src/Messages.js
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: enhancement

#768 Fix styling of autoacks alert on small screen sizes
  src/PresentationalComponents/ExecutiveReport/_Download.scss
  src/SmartComponents/Recs/List.scss
Labels: :godmode:, bug

#769 Add Redirect component for Classic ids
  locales/translations.json
  src/Messages.js
  src/SmartComponents/Recs/ClassicRedirect.js
  src/SmartComponents/Recs/Recs.js
Labels: :taco:, enhancement

#771 Update ClassicRedirect for urls with beta
  src/SmartComponents/Recs/ClassicRedirect.js
Labels: :vampire_woman:, bug

#770 Properly persist clearing the Red Hat disabled rule alert
  src/SmartComponents/Recs/List.js
Labels: bug

#772 Use paramsSerializer for tag param parsing, update deps 😀😃😄
  package-lock.json
  package.json
  src/PresentationalComponents/Common/Tables.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/PresentationalComponents/SystemsTable/SystemsTable.js
  src/SmartComponents/Recs/Details.js
  src/SmartComponents/Topics/List.js
  src/Utilities/Api.js
Labels: :taco:, enhancement

#775 Change rule_status param to suit api change
  src/AppConstants.js
  src/PresentationalComponents/Common/Tables.js
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: :1st_place_medal:, bug

#773 SID support, rec table all status filter param, adopt mapGlobalFilter 👩‍🏭
  src/App.js
  src/AppActions.js
  src/AppConstants.js
  src/AppReducer.js
  src/PresentationalComponents/Common/Tables.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/PresentationalComponents/SystemsTable/SystemsTable.js
  src/SmartComponents/Recs/Details.js
  src/SmartComponents/Topics/List.js
Labels: bug

#776 Removes tagstoolbar now that global filter exists🙇‍♂️📚
  locales/translations.json
  src/AppConstants.js
  src/Messages.js
  src/PresentationalComponents/TagsToolbar/Common.js
  src/PresentationalComponents/TagsToolbar/ManageTags.js
  src/PresentationalComponents/TagsToolbar/TagsToolbar.js
  src/PresentationalComponents/TagsToolbar/_TagsToolbar.scss
  src/SmartComponents/Recs/Details.js
  src/SmartComponents/Recs/List.js
  src/SmartComponents/Systems/List.js
  src/SmartComponents/Topics/Details.js
  src/SmartComponents/Topics/List.js
Labels: enhancement

#774 Display impacted_systems_count for disabled recommendations too
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: on hold

#777 Fixes SID w/new util that supports arrayEnhancers 😀😃😄😁, updates deps
  package-lock.json
  package.json
  src/PresentationalComponents/Common/Tables.js
Labels: :star2:, bug

#778 Update ClassicRedirect to consume systems/classic
  locales/translations.json
  src/Messages.js
  src/SmartComponents/Common/ClassicRedirect.js
  src/SmartComponents/Recs/Recs.js
  src/SmartComponents/Systems/Systems.js
Labels: :taco:, enhancement
