Repository RedHatInsights/insights-advisor-frontend, pull requests merged in 2020-06, with the labels that each got.

#655 Adds sorting by updated to rec details inventory table
  src/PresentationalComponents/Inventory/Inventory.js
  src/SmartComponents/Rules/Details.js
Labels: :+1:, :vampire_woman:, enhancement

#660 Impacting no longer required local to rec table component
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: bug

#659 Adds category filter to inv-insights plugin
  package-lock.json
  package.json
Labels: :+1:, enhancement

#658 Adds rule hit risk columns to systems table
  src/PresentationalComponents/SystemsTable/SystemsTable.js
Labels: enhancement, on hold

#661 Adds reboot required filter to rec table
  src/AppConstants.js
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: :waffle: :soap: :anchor: :namibia:, enhancement

#662 Update inv-insights n other deps 👩‍🏭🛠💯
  package-lock.json
  package.json
Labels: enhancement

#664 Persists cve alert status to session storage
  src/SmartComponents/InsightsTabs/InsightsTabs.js
Labels: enhancement

#667 Remove the static images. They are now in the frontend-assets repo.
  static/images/WN_export.png
  static/images/WN_filter.png
  static/images/criticalHits.png
  static/images/email/critical-hits-icon.png
  static/images/email/email-background.png
  static/images/email/rh-insights-logo.png
  static/images/email/total-hits-icon.png
  static/images/email/total-systems-icon.png
  static/images/graph.png
  static/images/rh-logo-white.svg
  static/images/rh.png
  static/images/servers.png
Labels: enhancement

#669 Adds json/csv export to system table
  src/Messages.js
  src/PresentationalComponents/Common/DownloadHelper.js
  src/PresentationalComponents/Common/Tables.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/PresentationalComponents/SystemsTable/SystemsTable.js
Labels: :waffle: :soap: :anchor: :namibia:, enhancement

#671 Manage all tags text always available 🤗👩‍🏭
  src/Messages.js
  src/PresentationalComponents/TagsToolbar/TagsToolbar.js
Labels: :taco:, enhancement

#673 Change system table text, updates deps, brings mergemessages.js locally
  locales/data.json
  locales/translations.json
  package-lock.json
  package.json
  src/Messages.js
  src/Utilities/mergeMessages.js
Labels: enhancement

#674 Adds sorting to system table hits columns
  src/PresentationalComponents/SystemsTable/SystemsTable.js
Labels: enhancement

#670 Filter systems table by whether or not the columns have hits
  src/AppConstants.js
  src/PresentationalComponents/Common/Tables.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/PresentationalComponents/SystemsTable/SystemsTable.js
Labels: enhancement

#676 System table to prioritize name columnsize
  src/PresentationalComponents/SystemsTable/SystemsTable.js
Labels: enhancement

#672 Add Filtering to Tags Selector
  src/AppConstants.js
  src/Messages.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/PresentationalComponents/SystemsTable/SystemsTable.js
  src/PresentationalComponents/TagsToolbar/TagsToolbar.js
  src/PresentationalComponents/TagsToolbar/_TagsToolbar.scss
Labels: enhancement

#679 Prevent systable debounce from 🤯 offset
  src/PresentationalComponents/SystemsTable/SystemsTable.js
Labels: bug

#677 Set Input's value to searchText when TagToolbar dropdown opens
  src/PresentationalComponents/TagsToolbar/TagsToolbar.js
Labels: enhancement

#678 More gracefully handle incorrect filter value
  src/PresentationalComponents/Common/Tables.js
Labels: bug

#680 Adds pdf export to systems table
  locales/data.json
  locales/translations.json
  src/Messages.js
  src/PresentationalComponents/Export/SystemsPdf.js
  src/PresentationalComponents/Export/SystemsPdfBuild.js
  src/PresentationalComponents/Export/_Export.scss
  src/PresentationalComponents/SystemsTable/SystemsTable.js
Labels: :waffle: :soap: :anchor: :namibia:, enhancement

#682 Improves sys-table pdf export compactness, updates deps
  package-lock.json
  package.json
  src/PresentationalComponents/Export/SystemsPdf.js
  src/PresentationalComponents/Export/SystemsPdfBuild.js
Labels: enhancement
