Repository RedHatInsights/insights-advisor-frontend, pull requests merged in 2020-04, with the labels that each got.

#607 Prune n update deps, version bump for rollup change
  package-lock.json
  package.json
Labels: enhancement

#608 Fix system table dupe calls
  package-lock.json
  src/PresentationalComponents/SystemsTable/SystemsTable.js
  src/PresentationalComponents/TagsToolbar/TagsToolbar.js
Labels: bug

#609 Update react-redux and pass store down to inventory
  package.json
  src/PresentationalComponents/Inventory/Inventory.js
  src/PresentationalComponents/Inventory/InventoryDetails.js
Labels: enhancement

#610 Update deps, strings and a grab 💰of things
  locales/data.json
  locales/translations.json
  package-lock.json
  package.json
  profiles/local-frontend.js
  src/Messages.js
Labels: enhancement

#612 Removes duplicate rec detail breadcrumb
  src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
Labels: enhancement

#614 Rec table Ansible filter placeholder is now capitalized
  package-lock.json
  package.json
  src/AppConstants.js
  src/PresentationalComponents/Common/Tables.js
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: enhancement

#615 Adds generic rec details to details component (details page only)
  src/PresentationalComponents/RuleDetails/RuleDetails.js
Labels: bug

#603 Add Executive Reporting
  package-lock.json
  package.json
  src/AppConstants.js
  src/PresentationalComponents/ExecutiveReport/Build.js
  src/PresentationalComponents/ExecutiveReport/Download.js
  src/PresentationalComponents/ExecutiveReport/_Download.scss
  src/SmartComponents/InsightsTabs/InsightsTabs.js
Labels: enhancement

#617 Adds tooltip to inv-advisor n other fixes
  package-lock.json
  package.json
Labels: enhancement

#616 Move dropdown position to onscreen
  src/SmartComponents/Rules/Details.js
Labels: bug

#611 [RFR] Fix bug where tag checkboxes remain checked
  src/PresentationalComponents/TagsToolbar/TagsList.js
Labels: bug

#618 Default rec table params include limit/offset 👈 set on clear all filters
  src/AppReducer.js
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: bug

#619 Removes sentence casing from breadcrumbs
  src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
Labels: enhancement

#620 Kills culling 🔪
  src/PresentationalComponents/SystemsTable/SystemsTable.js
Labels: bug

#621 Inv Advisor cleanup 👨‍🚒🍇🌌fixes exec reports multidownloads
  package-lock.json
  package.json
  src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
Labels: :taco:, bug, enhancement

#622 Turn off disable recs when selected.length = 0 in inventory
  src/PresentationalComponents/Inventory/Inventory.js
Labels: bug

#623 Updates kba url to use new api n client identifier
  package-lock.json
  package.json
Labels: :taco:, :vampire_woman:, bug

#624 Prevent multiple rendering when changing tabs
  src/PresentationalComponents/ExecutiveReport/Download.js
Labels: bug

#625 Changes cve redirect as per divine guidance 🥰🎈
  src/SmartComponents/Rules/Details.js
Labels: :vampire_woman:, enhancement

#626 If we're loading the exec report, disable the button
  src/PresentationalComponents/ExecutiveReport/Download.js
Labels: bug

#627 Rewords executive report
  locales/data.json
  locales/translations.json
  src/Messages.js
  src/PresentationalComponents/ExecutiveReport/Build.js
  src/PresentationalComponents/ExecutiveReport/Download.js
Labels: enhancement

#628 Fetch hostacks only once we have a rule_id, prevents dupe calls
  src/SmartComponents/Rules/Details.js
Labels: bug

#630 Swaps default rec sorting, publish_date, for total_risk
  src/AppReducer.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/SmartComponents/Topics/Details.js
Labels: enhancement

#631 Utilizes compound sorting to return exec reports top 3 recs
  src/PresentationalComponents/ExecutiveReport/Download.js
Labels: enhancement

#632 Rec table, remove search field when cleared by filter chips
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: bug

#629 Make system table pagination compact
  src/PresentationalComponents/SystemsTable/SystemsTable.js
Labels: bug

#633 Update non-breaking deps, babel-plugin-react-intl breaks build
  package-lock.json
  package.json
Labels: enhancement

#634 Add key press handler for disable rule modal
  src/PresentationalComponents/Modals/DisableRule.js
Labels: bug

#613 Use inventory when showing list of systems
  src/AppReducer.js
  src/PresentationalComponents/SystemsTable/SystemsTable.js
Labels: enhancement

#636 In lieu correct MD, adds styles to generic content, to match satellite
  src/PresentationalComponents/RuleDetails/RuleDetails.js
  src/PresentationalComponents/RuleDetails/_RuleDetails.scss
Labels: :vampire_woman:, enhancement

#637 Add error handling for remediations
  src/PresentationalComponents/Inventory/Inventory.js
Labels: :taco:, bug

#638 Updates deps, ALL TEH DEPS 🤸‍♀️👍🏽
  package-lock.json
  package.json
Labels: :taco:, enhancement
