Repository RedHatInsights/insights-advisor-frontend, pull requests merged in 2020-09, with the labels that each got.

#745 Updates deps, fixes translations, other lil 🦟🕷🐛🐜🐞
  locales/translations.json
  package-lock.json
  package.json
  profiles/local-frontend.js
  src/Utilities/mergeMessages.js
  src/index.html
Labels: :vampire_woman:, enhancement, tech debt

#746 Adds loading to rec details inventory table component
  src/PresentationalComponents/Inventory/Inventory.js
Labels: :waffle: :soap: :anchor: :namibia:, enhancement

#747 This work restores Advisor storing selected tags encoded
  src/App.js
Labels: :shrug:, bug

#748 Fixes global filter tagging, removes hardcoded chrome source
  profiles/local-frontend.js
  src/App.js
Labels: :star2:, bug

#749 Set flex value for Recs header
  src/SmartComponents/Recs/List.scss
Labels: :vampire_woman:, bug

#750 Keep Rec Header size consistent
  src/SmartComponents/Recs/List.scss
Labels: :taco:, bug

#751 For Dan, changeup how tags are encoded🛠🐡🧠
  src/App.js
  src/PresentationalComponents/TagsToolbar/TagsToolbar.js
Labels: :waffle: :soap: :anchor: :namibia:, enhancement

#752 Updates non-breaking deps
  package-lock.json
  package.json
Labels: :taco:, tech debt

#753 Default state of system table is show all systems🥰🦹‍♀️
  src/PresentationalComponents/SystemsTable/SystemsTable.js
Labels: enhancement

#754 Update deps ✅🥰
  package-lock.json
  package.json
Labels: tech debt

#758 Mark systems table as full view
  src/PresentationalComponents/SystemsTable/SystemsTable.js
Labels: :godmode:

#756 Adds workflow filter to advisor
  .eslintrc.yml
  src/App.js
  src/AppActions.js
  src/AppConstants.js
  src/AppReducer.js
  src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
  src/PresentationalComponents/Common/Tables.js
  src/PresentationalComponents/ExecutiveReport/Build.js
  src/PresentationalComponents/Export/SystemsPdfBuild.js
  src/PresentationalComponents/Inventory/Inventory.js
  src/PresentationalComponents/Modals/DisableRule.js
  src/PresentationalComponents/Modals/ViewHostAcks.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/PresentationalComponents/SystemsTable/SystemsTable.js
  src/SmartComponents/Recs/Details.js
  src/SmartComponents/Topics/Details.js
  src/SmartComponents/Topics/List.js
  src/cveToRuleid.js
Labels: :vampire_woman:, enhancement

#759 Updates deps, nothing breaks 🤯😝💪
  package-lock.json
  package.json
Labels: :waffle: :soap: :anchor: :namibia:, enhancement, tech debt

#757 Support for Red Hat disabled rules via API rule_status parameter
  locales/translations.json
  src/AppConstants.js
  src/AppReducer.js
  src/Messages.js
  src/PresentationalComponents/Modals/DisableRule.js
  src/PresentationalComponents/RuleLabels/RuleLabels.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/SmartComponents/Recs/Details.js
  src/SmartComponents/Recs/List.js
  src/SmartComponents/Recs/List.scss
  src/SmartComponents/Topics/Details.js
Labels: enhancement

#760 Only display Red Hat disabled rules alert if there are said rules
  src/SmartComponents/Recs/List.js
Labels: :godmode:, enhancement

#761 Fixes workloadahroo filterahroonie, removes rule_status undefined url
  src/App.js
  src/PresentationalComponents/Common/Tables.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/PresentationalComponents/SystemsTable/SystemsTable.js
  src/SmartComponents/Recs/Details.js
  src/SmartComponents/Topics/List.js
Labels: :waffle: :soap: :anchor: :namibia:, bug
