Repository RedHatInsights/insights-advisor-frontend, pull requests merged in 2020-05, with the labels that each got.

#639 Fix missing ul marker in nested lists
  package-lock.json
  package.json
Labels: bug

#640 Tags query param mirrors component selectedTag value 💪😝🥺😵
  src/PresentationalComponents/Common/Tables.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/PresentationalComponents/SystemsTable/SystemsTable.js
  src/PresentationalComponents/TagsToolbar/Common.js
  src/PresentationalComponents/TagsToolbar/TagsList.js
  src/PresentationalComponents/TagsToolbar/TagsToolbar.js
Labels: :taco:, enhancement

#641 Rec/sys table, dedupes tag calls, fixes param filter overwrite
  src/AppReducer.js
  src/PresentationalComponents/Common/Tables.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/PresentationalComponents/SystemsTable/SystemsTable.js
  src/PresentationalComponents/TagsToolbar/Common.js
  src/PresentationalComponents/TagsToolbar/TagsToolbar.js
  src/SmartComponents/Rules/Details.js
  src/SmartComponents/Topics/List.js
Labels: bug

#642 Update non-breaking deps
  package-lock.json
  package.json
Labels: enhancement

#643 Update deps, clean up babelrc
  .babelrc
  .eslintignore
  package-lock.json
  package.json
Labels: enhancement

#644 Add TagToolbar component to Topics detail page
  src/SmartComponents/Topics/Details.js
Labels: enhancement

#645 Adds support for local storage, persists state with valid value
  src/AppReducer.js
  src/Store/index.js
Labels: :taco:, enhancement

#650 Update cveToRuleid mapping to remove SMBloris rules
  src/cveToRuleid.js
Labels: bug

#646 Update non-breakping deps
  config/prod.webpack.config.js
  package-lock.json
  package.json
Labels: enhancement

#651 Fix bulk select check calculation, isSelected calculated off rule_id
  package-lock.json
  package.json
Labels: :taco:, enhancement

#652 Modifies titles for Likelihood & Impact scale
  locales/data.json
  locales/translations.json
  src/AppConstants.js
  src/Messages.js
Labels: :taco:, enhancement

#654 Adds sorting to name column of rec details inventory table
  src/AppActions.js
  src/PresentationalComponents/Inventory/Inventory.js
  src/SmartComponents/Rules/Details.js
Labels: :taco:, enhancement

#656 Update deps, clear up build warning
  package-lock.json
  package.json
  src/PresentationalComponents/Inventory/InventoryDetails.js
Labels: enhancement
