Repository RedHatInsights/insights-advisor-frontend, pull requests merged in 2021-01, with the labels that each got.

#788 Update deps 🥳🥳🥳
  package-lock.json
  package.json
Labels: :vampire_woman:

#789 Remove Red Hat from insights
  src/index.html
Labels: :godmode:

#791 [RFR]Added ouiaid attributes to all UI components
  src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
  src/PresentationalComponents/Modals/AddEditTopic.js
  src/PresentationalComponents/Modals/DisableRule.js
  src/PresentationalComponents/RuleRating/RuleRating.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/PresentationalComponents/TopicsAdminTable/TopicsAdminTable.js
  src/PresentationalComponents/TopicsTable/TopicsTable.js
  src/SmartComponents/Recs/Details.js
  src/SmartComponents/Topics/Details.js
Labels: enhancement

#784 Add federated modules generation and custom plugins
  config/dev.webpack.config.js
  config/prod.webpack.config.js
  locales/translations.json
  package-lock.json
  package.json
  profiles/local-frontend.js
  src/AppConstants.js
  src/AppEntry.js
  src/PresentationalComponents/Inventory/Inventory.js
  src/PresentationalComponents/Inventory/InventoryDetails.js
  src/PresentationalComponents/SystemsTable/SystemsTable.js
  src/Routes.js
  src/SmartComponents/Recs/List.js
  src/bootstrap-dev.js
  src/bootstrap.js
  src/entry-dev.js
  src/entry.js
  src/index.html
Labels: :star2:, :taco:, enhancement

#792 Changes rec detail topic to not be in a card 🤷‍♀️🤯
  src/PresentationalComponents/RuleDetails/RuleDetails.js
Labels: :shrug:, enhancement

#793 Update deps, fec v2 👉 v3 🥰🥰🥰🥰🥰
  package-lock.json
  package.json
  src/App.js
  src/App.scss
  src/AppEntry.js
  src/AppReducer.js
  src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
  src/PresentationalComponents/Common/DownloadHelper.js
  src/PresentationalComponents/Common/Tables.js
  src/PresentationalComponents/Inventory/Inventory.js
  src/PresentationalComponents/Inventory/InventoryDetails.js
  src/PresentationalComponents/Modals/ViewHostAcks.js
  src/PresentationalComponents/RuleDetails/RuleDetails.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/PresentationalComponents/SystemsTable/SystemsTable.js
  src/PresentationalComponents/TopicsAdminTable/TopicsAdminTable.js
  src/PresentationalComponents/TopicsTable/TopicsTable.js
  src/SmartComponents/Recs/Details.js
  src/SmartComponents/Recs/Details.scss
  src/SmartComponents/Recs/List.js
  src/SmartComponents/Systems/List.js
  src/SmartComponents/Topics/Details.js
  src/SmartComponents/Topics/List.js
  src/SmartComponents/Topics/_Details.scss
  src/Store/index.js
Labels: :godmode:, enhancement
