Repository RedHatInsights/insights-advisor-frontend, pull requests merged in 2021-08, with the labels that each got.

#857 Fixes breadcrumbs, sets us up for pathways support 🗺🤓
  src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
  src/PresentationalComponents/Inventory/InventoryDetails.js
  src/SmartComponents/Recs/Details.js
  src/SmartComponents/Topics/Details.js
  src/SmartComponents/Topics/List.js
Labels: :taco:, bug

#856 Reconfigures a few folders, hooks up Pathways panel to da store
  package-lock.json
  package.json
  profiles/local-frontend.js
  src/App.js
  src/AppEntry.js
  src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
  src/PresentationalComponents/Inventory/Inventory.js
  src/PresentationalComponents/Inventory/InventoryDetails.js
  src/PresentationalComponents/Modals/AddEditTopic.js
  src/PresentationalComponents/Modals/DisableRule.js
  src/PresentationalComponents/Modals/ViewHostAcks.js
  src/PresentationalComponents/PathwaysPanel/PathwaysPanel.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/PresentationalComponents/SystemsTable/SystemsTable.js
  src/PresentationalComponents/TopicsAdminTable/TopicsAdminTable.js
  src/Services/Pathways.js
  src/SmartComponents/Recs/Details.js
  src/SmartComponents/Topics/Details.js
  src/SmartComponents/Topics/List.js
  src/Store/AppActions.js
  src/Store/AppReducer.js
  src/Store/index.js
  src/bootstrap-dev.js
  src/bootstrap.js
  src/entry-dev.js
Labels: enhancement

#858 Adds rec details as a federated module for OCPAF consumption
  config/dev.webpack.config.js
  config/prod.webpack.config.js
  src/PresentationalComponents/RuleDetails/index.js
Labels: enhancement

#859 Apply advisor styling in inventory application
  config/dev.webpack.config.js
  config/prod.webpack.config.js
Labels: bug

#862 updates to help keep data.json inline with translation files
  locales/data.json
  locales/translations.json
  package-lock.json
  package.json
  scripts/createDataJson.js
Labels: enhancement, :star2:

#863 Allows for xml to be rendered in report details
  package-lock.json
  package.json
  src/PresentationalComponents/ReportDetails/ReportDetails.js
Labels: bug, :shrug:

#861 Make RuleDetails fed module compatible with OCP rules
  config/dev.webpack.config.js
  src/PresentationalComponents/RuleDetails/RuleDetails.js
  src/PresentationalComponents/RuleRating/RuleRating.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/SmartComponents/Recs/Details.js
Labels: enhancement

#864 Make riskOfChange optional: rule details component
  src/PresentationalComponents/RuleDetails/RuleDetails.js
Labels: enhancement, :godmode:

#865 Hide feedback form if there is no onFeedbackChanged provided
  src/PresentationalComponents/RuleDetails/RuleDetails.js
Labels: enhancement

#867 Pathways no data state added, hooked up card to api, update deps 🙏🤙🏾🧐
  package-lock.json
  package.json
  src/Messages.js
  src/PresentationalComponents/PathwaysPanel/PathwaysPanel.js
  src/Services/Pathways.js
Labels: enhancement
