Repository RedHatInsights/insights-advisor-frontend, pull requests merged in 2021-02, with the labels that each got.

#794 Fixes pdf generator charts
  package-lock.json
  package.json
  src/PresentationalComponents/ExecutiveReport/Build.js
Labels: :waffle: :soap: :anchor: :namibia:, bug

#795 Update deps 👩‍🏫🍔✂️
  package-lock.json
  package.json
  src/PresentationalComponents/RuleDetails/RuleDetails.js
Labels: :shrug:, tech debt

#796 Federated modules debugging
  package-lock.json
  package.json
  profiles/local-frontend.js
  src/App.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/Routes.js
Labels: :godmode:, enhancement

#797 Update deps 👩‍🏫🍔😇
  package-lock.json
  package.json
Labels: :1st_place_medal:, tech debt

#798 Adds support for pdf export group names
  locales/translations.json
  package-lock.json
  package.json
  src/Messages.js
  src/PresentationalComponents/ExecutiveReport/Download.js
  src/PresentationalComponents/Export/SystemsPdf.js
Labels: enhancement
