Repository RedHatInsights/insights-advisor-frontend, pull requests merged in 2021-06, with the labels that each got.

#825 Update deps 🐊🍟🛹
  package-lock.json
  package.json
Labels: :1st_place_medal:, enhancement

#826 Fix sentence case, also npm audit
  package-lock.json
  package.json
  src/PresentationalComponents/Inventory/Inventory.js
Labels: bug

#827 Removes rh disabled rules alert from rec page
  src/SmartComponents/Recs/List.js
Labels: enhancement

#828 RH disabled filter now shows n/a systems with info tooltip
  locales/translations.json
  src/Messages.js
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: :star2:, enhancement

#830 Update deps 🥽🎩🔱
  package-lock.json
  package.json
Labels: :1st_place_medal:, :shrug:

#832 Update travis-ci links in README.md
  README.md
Labels: bug

#831 Use compact tables for systems/recs and page size 20
  src/AppReducer.js
  src/PresentationalComponents/RulesTable/RulesTable.js
  src/PresentationalComponents/SystemsTable/SystemsTable.js
Labels: enhancement

#833 Add default for undefined items
  src/PresentationalComponents/Inventory/Inventory.js
Labels: bug

#834 Updates filter wording as per UX request
  locales/translations.json
  src/AppConstants.js
  src/Messages.js
Labels: :vampire_woman:, enhancement

#835 Rollback fec cuz inventory table issues
  package-lock.json
  package.json
Labels: bug

#836 Updates report detail table to use pf select/disabled select
  package-lock.json
  package.json
  src/SmartComponents/SystemAdvisor/SystemAdvisor.js
Labels: bug

#838 Rule details mobile fixes
  package-lock.json
  package.json
  src/PresentationalComponents/RuleDetails/_RuleDetails.scss
Labels: :godmode:, bug

#839 Reduce font size in compact table expanded view
  locales/translations.json
  src/Messages.js
  src/PresentationalComponents/RuleDetails/_RuleDetails.scss
Labels: bug

#840 Fixes systems page infinity loading issue
  package-lock.json
  src/PresentationalComponents/SystemsTable/SystemsTable.js
Labels: bug

#841 Updates inv tables as per InventoryTable post-summit refactoring plan 🍟
  src/PresentationalComponents/Inventory/Inventory.js
  src/PresentationalComponents/SystemsTable/SystemsTable.js
Labels: enhancement

#842 Update deps, add beta start, relocate rec name badge 🪃🇹🇹🪂
  config/dev.webpack.config.js
  package-lock.json
  package.json
  src/PresentationalComponents/RulesTable/RulesTable.js
Labels: :vampire_woman:, enhancement

#843 fun timez making getEntities workin
  src/AppReducer.js
  src/PresentationalComponents/SystemsTable/SystemsTable.js
Labels: :star2:, bug
