Repository RedHatInsights/insights-advisor-frontend, pull requests merged in 2022-11, with the labels that each got.

#1035 feat(SystemAdvisor): ADVISOR-2783 - Add first impacted column
  cypress/fixtures/systemRecommendations.json
  cypress/support/component.js
  cypress/support/globals.js
  locales/data.json
  locales/translations.json
  package.json
  src/Messages.js
  src/SmartComponents/SystemAdvisor/SystemAdvisor.cy.js
  src/SmartComponents/SystemAdvisor/SystemAdvisor.js
Labels: enhancement

#1045 fix: Add federated module wrapper for SystemAdvisor
  config/dev.webpack.config.js
  config/prod.webpack.config.js
  src/Modules/SystemDetail.js
  src/SmartComponents/SystemAdvisor/SystemAdvisor.js
Labels: bug

#1043 fix(SystemAdvisor): show rules for satellite managed hosts
  src/SmartComponents/SystemAdvisor/EmptyStates.js
  src/SmartComponents/SystemAdvisor/SystemAdvisor.js
Labels: bug, don't merge

#1044 feat(CodeCov): add codecoverage to the repo
  .babelrc
  .github/workflows/cypress.yml
  .gitignore
  .travis.yml
  README.md
  coverage.sh
  cypress.config.js
  cypress/support/component.js
  package-lock.json
  package.json
Labels: enhancement

#1058 test(Recs list): Test filter query parameters
  cypress/support/globals.js
  src/PresentationalComponents/RulesTable/RulesTable.cy.js
Labels: component tests

#1059 feat(RecsListTests): sorting tests
  package.json
  src/PresentationalComponents/RulesTable/RulesTable.cy.js
Labels: enhancement, :godmode:
