Repository RedHatInsights/insights-advisor-frontend, pull requests merged in 2022-12, with the labels that each got.

#1063 chore(RulesTable): cleaning up the test file
  src/PresentationalComponents/RulesTable/RulesTable.cy.js
Labels: tech debt

#1065 test(topics table): Sorting refactor and testing the Topics table
  .github/workflows/CI.yml
  cypress/fixtures/topics.json
  cypress/support/globals.js
  src/PresentationalComponents/TopicsTable/TopicsTable.cy.js
  src/PresentationalComponents/TopicsTable/TopicsTable.js
  src/PresentationalComponents/helper.js
  src/PresentationalComponents/helper.test.js
Labels: enhancement

#1069 chore(tests): Check the default filter for RulesTable
  src/PresentationalComponents/RulesTable/RulesTable.cy.js
Labels: component tests

#1070 test(Pathways tab): cypress tests
  cypress/fixtures/pathways.json
  cypress/support/globals.js
  src/PresentationalComponents/PathwaysTable/PathwaysTable.cy.js
Labels: component tests

#1073 fix(Shared dependencies): Align versions of redux
  package-lock.json
  package.json
Labels: dependencies
