Repository RedHatInsights/insights-advisor-frontend, pull requests merged in 2023-11, with the labels that each got.

#1187 feat(ADVISOR-3185) - Risk Labels refactor
  locales/data.json
  locales/translations.json
  src/Messages.js
  src/PresentationalComponents/RulesTable/helpers.js
  src/Utilities/intlHelper.js
Labels: enhancement

#1191 chore(RTL): install rtl related dev dependencies
  .eslintrc.yml
  config/setupTests.js
  package-lock.json
  package.json
  src/PresentationalComponents/Inventory/Hooks/useBulkSelect/__snapshots__/useBulkSelect.test.js.snap
  src/PresentationalComponents/Inventory/Hooks/useSelectionManager/__snapshots__/useSelectionManager.test.js.snap
  src/SmartComponents/HybridInventoryTabs/ImmutableDevices.test.js
  src/Utilities/TestingUtilities.js
Labels: blocker

#1194 fix(ImmutableDevices): pass edge filer into custom filter prop
  src/SmartComponents/HybridInventoryTabs/ImmutableDevices.js
Labels: bug

#1197 feat(RHINENG-3070): implement two tabs in pathway details page
  src/Routes.js
  src/SmartComponents/HybridInventoryTabs/ConventionalSystems/PathwaySystems.js
  src/SmartComponents/HybridInventoryTabs/HybridInventoryTabs.js
  src/SmartComponents/HybridInventoryTabs/HybridInventorytabs.test.js
  src/SmartComponents/HybridInventoryTabs/ImmutableDevices.js
  src/SmartComponents/HybridInventoryTabs/helpers.js
  src/SmartComponents/HybridInventoryTabs/helpers.test.js
  src/SmartComponents/Recs/Details.js
  src/SmartComponents/Recs/DetailsPathways.js
  src/SmartComponents/Recs/helpers.js
  src/SmartComponents/Recs/helpers.test.js
Labels: enhancement
