Repository RedHatInsights/insights-advisor-frontend, pull requests merged in 2023-12, with the labels that each got.

#1205 feat(RHINENG-3631): Recommendations Page - Adding OverviewDashbar
  locales/data.json
  locales/translations.json
  package-lock.json
  package.json
  src/AppConstants.js
  src/Messages.js
  src/PresentationalComponents/Cards/OverviewDashbarCard/OverviewDashbarCard.js
  src/PresentationalComponents/Cards/OverviewDashbarCard/__tests__/DashbarCardTagOrIcon.test.js
  src/PresentationalComponents/Cards/OverviewDashbarCard/__tests__/DashbarCardTitle.test.js
  src/PresentationalComponents/Cards/OverviewDashbarCard/__tests__/OverviewDashbarCard.test.js
  src/PresentationalComponents/Cards/OverviewDashbarCard/__tests__/TagLabelWithTooltip.test.js
  src/PresentationalComponents/Cards/OverviewDashbarCard/components/DashbarCardTagOrIcon/DashbarCardTagOrIcon.js
  src/PresentationalComponents/Cards/OverviewDashbarCard/components/DashbarCardTagOrIcon/TagLabelWithTooltip.js
  src/PresentationalComponents/Cards/OverviewDashbarCard/components/DashbarCardTitle/DashbarCardTitle.js
  src/PresentationalComponents/Cards/OverviewDashbarCard/components/DashbarCardTitle/TitleWithTooltip.js
  src/PresentationalComponents/Cards/PathwayCard.js
  src/PresentationalComponents/Common/Common.js
  src/PresentationalComponents/Labels/RuleLabels.js
  src/PresentationalComponents/Loading/Loading.js
  src/PresentationalComponents/MessageState/MessageState.js
  src/PresentationalComponents/OverviewDashbar/Hooks/useApplyFilters/useApplyFilters.js
  src/PresentationalComponents/OverviewDashbar/Hooks/useOverviewData/useOverviewData.js
  src/PresentationalComponents/OverviewDashbar/OverviewDashbar.js
  src/PresentationalComponents/OverviewDashbar/__tests__/OverviewDashbar.test.js
  src/PresentationalComponents/PathwaysPanel/PathwaysPanel.js
  src/PresentationalComponents/PathwaysPanel/_PathwaysPanel.scss
  src/Services/Filters.js
  src/Services/Overview.js
  src/SmartComponents/Recs/List.js
  src/Utilities/unitTestingUtilities.js
Labels: enhancement

#1208 feat(RHINENG-5544): Remove Application Name Prefix From Titles
  src/SmartComponents/Recs/List.js
  src/SmartComponents/Systems/List.js
  src/SmartComponents/Topics/List.js
Labels: ux/approved

#1218 fix(Inventory): remove extra sorting icon on inventory tables
  src/PresentationalComponents/Inventory/Inventory.js
  src/PresentationalComponents/SystemsTable/SystemsTableAssets.js
Labels: bug
